// lisa_particles.lslp 
// 2017-03-14 01:17:06 - LSLForge (0.1.9.3) generated
default {

    state_entry() {
    llParticleSystem([PSYS_SRC_PATTERN,PSYS_SRC_PATTERN_EXPLODE,PSYS_SRC_BURST_RADIUS,1,PSYS_SRC_ANGLE_BEGIN,0,PSYS_SRC_ANGLE_END,0,PSYS_SRC_TARGET_KEY,llGetKey(),PSYS_PART_START_COLOR,<1.0,1.0,1.0>,PSYS_PART_END_COLOR,<1.0,0.0,0.0>,PSYS_PART_START_ALPHA,1,PSYS_PART_END_ALPHA,1,PSYS_PART_START_GLOW,0.1,PSYS_PART_END_GLOW,0,PSYS_PART_BLEND_FUNC_SOURCE,PSYS_PART_BF_SOURCE_ALPHA,PSYS_PART_BLEND_FUNC_DEST,PSYS_PART_BF_ONE_MINUS_SOURCE_ALPHA,PSYS_PART_START_SCALE,<0.5,0.5,0.0>,PSYS_PART_END_SCALE,<0.5,0.5,0.0>,PSYS_SRC_TEXTURE,"",PSYS_SRC_MAX_AGE,0,PSYS_PART_MAX_AGE,5,PSYS_SRC_BURST_RATE,0.3,PSYS_SRC_BURST_PART_COUNT,9,PSYS_SRC_ACCEL,<0.5,0.4,0.6>,PSYS_SRC_OMEGA,<0.0,0.0,0.0>,PSYS_SRC_BURST_SPEED_MIN,0.2,PSYS_SRC_BURST_SPEED_MAX,0.5,PSYS_PART_FLAGS,((0 | PSYS_PART_INTERP_COLOR_MASK) | PSYS_PART_RIBBON_MASK)]);
  }
}
